# Configurazione Database H2 (File locale)
spring.datasource.url=jdbc:h2:file:./safecore_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
# update: crea le tabelle automaticamente se non esistono
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Permette di vedere la console di H2 nel browser (utile per debug)
spring.h2.console.enabled=true